## Numpy Array Operations

In [8]:
import numpy as np

In [9]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print('Basic Slicing',arr[2:7])
print('With Steps',arr[1:8:2])
print('Negative indexing',arr[-3])


Basic Slicing [3 4 5 6 7]
With Steps [2 4 6 8]
Negative indexing 8


In [10]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Specific element',arr_2d[1,2])
print('entire row',arr_2d[1])
print('entire column',arr_2d[:,1])


Specific element 6
entire row [4 5 6]
entire column [2 5 8]


## Sorting


In [11]:
unsorted = np.array([6,3,9,1,4])
print('Sorted Array',np.sort(unsorted))

arr_2d_unsorted = np.array([[2,3],[1,5],[8,4]])
print('Sorted 2d array by column\n',np.sort(arr_2d_unsorted,axis=0))
print('Sorted 2d array by row\n',np.sort(arr_2d_unsorted,axis=1))

Sorted Array [1 3 4 6 9]
Sorted 2d array by column
 [[1 3]
 [2 4]
 [8 5]]
Sorted 2d array by row
 [[2 3]
 [1 5]
 [4 8]]


### Filter

In [12]:
numbers = np.arange(11)
even_number = numbers[numbers%2==0]
print('even numbers',even_number)


even numbers [ 0  2  4  6  8 10]


#### filter with mask

In [13]:
mask = numbers>5
print('Numbers greater than 5',numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


## Fancy indexing vs np.where()


In [14]:
indices = [0,2,3]
print(even_number[indices])


[0 4 6]


## np.where()

### syntax 
numpy.where(condition, [x, y])

If only condition is given → returns the indices where condition is True.

If x and y are also given → returns values from x where condition is True, otherwise from y.


In [15]:
ar = np.array([10,20,30,40,50])
result = np.where(ar>23)

print('indices where condition is true',result)
print('value on where clouse indices',ar[result])

# Replace values: if > 25 keep same, else set -1
result = np.where((ar > 25 ) & (ar%2==0), ar, -1)
print(result)

indices where condition is true (array([2, 3, 4]),)
value on where clouse indices [30 40 50]
[-1 -1 30 40 50]


### Adding and removing data

Functions like np.append, np.insert, np.delete → return new arrays (they don’t modify in-place).

For efficiency, if you need frequent insertions/removals, use Python lists or Pandas instead.

In [16]:
# not use like adding list because it is vector or matrix
print(ar+ar)

arr = np.array([10, 20, 30])
new_arr = np.insert(arr, 1, 15)   # insert 15 at index 1

print(new_arr)   # [10 15 20 30]


# Adding elements
added = np.append(ar, [60, 70])
print('Array after adding elements:', added)

# concatinate 
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))

print(c)   # [1 2 3 4 5 6]

# removing element at index 2
new_a = np.delete(a,2)
print('deted element at index 2',new_a)

# Removing elements (e.g., remove element at index 1 and 3)
removed = np.delete(ar, [1, 3])
print('Array after removing elements at indices 1 and 3:', removed)

arr = np.array([10, 20, 30, 40, 50])
new_arr = arr[arr != 30]   # remove all 30s

print(new_arr)   # [10 20 40 50]

# Delete a row

a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print('array a \n',a)

new_a = np.delete(a, 1, axis=0)   # delete row index 1

print('delete 1\'st row\n',new_a)


# Delete a column

new_a = np.delete(a, 0, axis=1)   # delete column index 0

print('delete 0rth cloumn\n',new_a)

# Delete multiple rows or columns
# delete rows 0 and 2
rows_deleted = np.delete(a, [0, 2], axis=0)
print('delete rows 0 and 2\n',rows_deleted)
# [[4 5 6]]

# delete columns 1 and 2
cols_deleted = np.delete(a, [1, 2], axis=1)
print('delete columns 1 and 2\n',cols_deleted)
# [[1]
#  [4]
#  [7]]



[ 20  40  60  80 100]
[10 15 20 30]
Array after adding elements: [10 20 30 40 50 60 70]
[1 2 3 4 5 6]
deted element at index 2 [1 2]
Array after removing elements at indices 1 and 3: [10 30 50]
[10 20 40 50]
array a 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
delete 1'st row
 [[1 2 3]
 [7 8 9]]
delete 0rth cloumn
 [[2 3]
 [5 6]
 [8 9]]
delete rows 0 and 2
 [[4 5 6]]
delete columns 1 and 2
 [[1]
 [4]
 [7]]


## array compatibility

In [17]:
original = np.array([[1,2],[2,3]])
new_row = np.array([[5,6]])
with_new_row = np.vstack((original,new_row))
print('original\n',original)
print('with new row\n',with_new_row)

new_col = np.array([[3],[4],[5]])
with_new_col = np.hstack((with_new_row,new_col))
print('with new col\n',with_new_col)

original
 [[1 2]
 [2 3]]
with new row
 [[1 2]
 [2 3]
 [5 6]]
with new col
 [[1 2 3]
 [2 3 4]
 [5 6 5]]


In [18]:
arr = np.array()

TypeError: array() missing required argument 'object' (pos 0)

### 1. Elementwise Operation 
NumPy applies operations element by element, but shapes must be compatible.


In [4]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

print(x + y)  
print(x * y)  


[11 22 33]
[10 40 90]


### 2. Broadcasting Rules

Broadcasting is NumPy’s way of handling arrays with different shapes.

👉 Rule 1: If arrays have different dimensions, pad the smaller shape with 1s on the left.

👉 Rule 2: Compare shapes dimension by dimension:

If they are equal → ✅ compatible.

If one is 1 → ✅ compatible (it gets stretched).

Otherwise → ❌ not compatible.

compatible Shapes

In [ ]:

a = np.array([1, 2, 3])      # shape (3,)
b = np.array([[10], [20]])   # shape (2,1)

print(a + b)


[[11 12 13]
 [21 22 23]]


In [3]:
a = np.array([1, 2, 3])     # (3,)
b = np.array([10, 20])      # (2,)

print(a + b)   # ❌ ValueError: operands could not be broadcast


ValueError: operands could not be broadcast together with shapes (3,) (2,) 

Scalar Broadcasting

In [51]:
a = np.array([1, 2, 3])
print(a + 10)   # [11 12 13]


[11 12 13]


Row & Column Vector Broadcasting

In [52]:
row = np.array([[1, 2, 3]])   # shape (1,3)
col = np.array([[1], [2], [3]]) # shape (3,1)

print(row + col)


[[2 3 4]
 [3 4 5]
 [4 5 6]]


Higher Dimensions Broadcasting

In [56]:
a = np.ones((2,3,1))   # shape (2,3,1)
b = np.ones((1,1,4))   # shape (1,1,4)

print("shape\n",(a + b).shape)   # (2,3,4)
print('array\n',(a + b)) 


shape
 (2, 3, 4)
array
 [[[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]

 [[2. 2. 2. 2.]
  [2. 2. 2. 2.]
  [2. 2. 2. 2.]]]


Reshape for Compatibility

In [57]:
a = np.array([1,2,3])         # (3,)
b = np.array([10,20,30,40,50,60])  # (6,)

# reshape b into (2,3)
b = b.reshape(2,3)
print(a + b)


[[11 22 33]
 [41 52 63]]


### Practical Uses

Adding bias terms in ML: (n_samples, n_features) + (1, n_features)

Normalizing data: (n_samples, n_features) / (1, n_features)

Expanding dimensions for compatibility:

In [1]:
a = np.array([1, 2, 3])       # (3,)
print(a[:, np.newaxis].shape) # (3,1)


NameError: name 'np' is not defined