## Numpy array and basics
learn about numpy 

##Phase 1

In [1]:
import numpy as np
import time

## creating array from list

In [ ]:
arr_1d = np.array([1,2,3,4,5])
print('1D array\n',arr_1d)
arr_2d = np.array([[1,2,3],[4,5,6]])
print('2 D array\n',arr_2d)
print(arr_1d.dtype)

1D array
 [1 2 3 4 5]
2 D array
 [[1 2 3]
 [4 5 6]]
int64
specified number of elements, and spaced equally between the specified beginning and end values
 [1.  1.6 2.2 2.8 3.4 4. ]


### Intrinsic NumPy array creation functions

In [20]:
# 1D array creation functions
print('1D array creation functions\n')
x= np.arange(10)
print('\n',x)

x= np.arange(2, 10, dtype=float)
print('\n',x)

x= np.arange(2, 3, 0.1)
print('\n',x)


# 2D array creation functions
print('\n2D array creation functions\n')

x = np.eye(3)
print('\n',x)

x = np.eye(3,5)
print('\n',x)



# np.diag(v,k) square 2D matrix

x = np.diag([1,2,3])
print('\n',x)

# v can be 1D or 2D
# k = 0 main diagonal
# k>0 above main diagonal
# k < 0 below main diagonal
x = np.diag([1,2,3],1)
print('\n',x)

# return 1D
x =  np.array([[1,2],[2,4]])
x = np.diag(x)
print('\n',x)


1D array creation functions


 [0 1 2 3 4 5 6 7 8 9]

 [2. 3. 4. 5. 6. 7. 8. 9.]

 [2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]

2D array creation functions


 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

 [[1 0 0]
 [0 2 0]
 [0 0 3]]

 [[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]

 [1 4]


### List vs numpy array

In [11]:
py_list = [1,2,3,4]
print('Python list multiplication\n',py_list*2)

np_array = np.array([1,2,3,4])
print('Python list multiplication\n',np_array*2)

start = time.time()
py_list = [1*2 for i in range(1000000)]
print('list operation time',time.time()-start)

start = time.time()
np_array = np.arange(100000)*2
print('Numpy operation time',time.time()-start)



Python list multiplication
 [1, 2, 3, 4, 1, 2, 3, 4]
Python list multiplication
 [2 4 6 8]
list operation time 0.07384514808654785
Numpy operation time 0.0008568763732910156


## creating array from scratch

In [24]:
zeros = np.zeros((2,2))
print('Zero array :\n',zeros)

ones = np.ones((2,2))
print('one array:\n',ones)

full = np.full((2,2),7)
print('full array: \n',full)

random = np.random.random((2,3))
print('random array: \n',random)

sequence = np.arange(0,10,2)
print('sequence array: \n',sequence)




Zero array :
 [[0. 0.]
 [0. 0.]]
one array:
 [[1. 1.]
 [1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.2272409  0.73190554 0.24937908]
 [0.46145515 0.84297856 0.82857759]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tenser


In [25]:
vector = np.array([1,2,3,4])
print('Vector:\n ',vector)

matrix = np.array([[1,2,3],[1,2,3]])
print('matrix:\n ',matrix)

tenser = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print('tenser:\n',tenser)


Vector:
  [1 2 3 4]
matrix:
  [[1 2 3]
 [1 2 3]]
tenser:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [26]:
arr = np.array([[1,2,3],[4,5,6]])
print('Shape ',arr.shape)
print('Dimension ',arr.ndim)
print('Size ',arr.size)
print('DType ',arr.dtype)


Shape  (2, 3)
Dimension  2
Size  6
DType  int64


### Array Reshaping

In [9]:
arr = np.arange(0,12)
print('original array\n',arr)

reshaped = arr.reshape((3,4))
print('reshaped array\n',reshaped)

# or
a = [1,2,4,3,5,6]
print('convert list into array and reshaped\n',np.reshape(a,(2,3)))

flattend = reshaped.flatten()
print('flattend\n',flattend)

# ravel ( return view, insted of copy)
raveled = reshaped.ravel()
print('raveled\n',raveled)

transpose = reshaped.T
print('Transpose\n',transpose)




original array
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
convert list into array and reshaped
 [[1 2 4]
 [3 5 6]]
flattend
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transpose
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [22]:


A = np.eye(2)       # 2x2 identity
B = np.ones((2,2))  # 2x2 ones
C = 2 * np.ones((2,2))
print('\n',A)
print('\n',B)
print('\n',C)
M = np.block([[A, B],
              [C, A]])

print('\n',M)



 [[1. 0.]
 [0. 1.]]

 [[1. 1.]
 [1. 1.]]

 [[2. 2.]
 [2. 2.]]

 [[1. 0. 1. 1.]
 [0. 1. 1. 1.]
 [2. 2. 1. 0.]
 [2. 2. 0. 1.]]
